const fs=require('fs');let p='scripts/game.gd',s=fs.readFileSync(p,'utf8');
s=s.replace('var camp_clock=0','var camp_clock=0');
s=s.replace('var camp_clock = 0.0','var camp_clock = 0.0');
s=s.replace('func build_camp():','func camp_site() -> Vector3:\n\tvar best = Vector3(0, 0, 7)\n\tvar score = INF\n\tfor i in range(24):\n\t\tvar a = i * TAU / 24\n\t\tvar p = Vector3(sin(a) * 6.5, 0, cos(a) * 6.5)\n\t\tvar h = world.drive_height(van.position.x + p.x, van.position.z + p.z)\n\t\tvar variation = abs(h - van.position.y) * 0.5\n\t\tfor j in range(8):\n\t\t\tvar q = van.position + p + Vector3(sin(j * TAU / 8) * 2.6, 0, cos(j * TAU / 8) * 2.6)\n\t\t\tvariation += abs(world.drive_height(q.x, q.z) - h)\n\t\t\tif world.camera_blocked(Vector3(q.x, h + 1.8, q.z)): variation += 10\n\t\tif variation < score:\n\t\t\tscore = variation\n\t\t\tbest = p\n\tbest.y = world.drive_height(van.position.x + best.x, van.position.z + best.z) - van.position.y + 0.25\n\treturn best\n\nfunc build_camp():');
s=s.replace('var fire_pos = Vector3(-5, 0, -0.5)\n\tfire_pos.y = world.drive_height(van.position.x - 5, van.position.z - 0.5) - van.position.y + 0.25','var fire_pos = camp_site()\n\tcamp.set_meta("focus", fire_pos * 0.55 + Vector3(0, 1.5, 0))\n\tvar aim = van.position + camp.get_meta("focus")\n\tvar best_view = -INF\n\tfor i in range(24):\n\t\tvar a = i * TAU / 24\n\t\tvar desired = aim + Vector3(sin(a) * cos(0.5), sin(0.5), -cos(a) * cos(0.5)) * 17\n\t\tvar clear = world.safe_camera(aim, desired).distance_to(aim)\n\t\tvar view_score = clear - world.ground(desired.x, desired.z) * 0.015\n\t\tif view_score > best_view:\n\t\t\tbest_view = view_score\n\t\t\torbit_yaw = a');
s=s.replace('look = camera_anchor + (Vector3(-3, 1, 0) if camping else Vector3(0, 1.6, 0))','look = camera_anchor + (camp.get_meta("focus", Vector3(0, 1.6, 0)) if camping and is_instance_valid(camp) else Vector3(0, 1.6, 0))');
s=s.replace('\n\t\ttarget.y = maxf(target.y, world.ground(target.x, target.z) + 0.7)','');
fs.writeFileSync(p,s);
p='shaders/gravel.gdshader';s=fs.readFileSync(p,'utf8');s=s.replace('void vertex()',`float noise(vec2 p) { vec2 i=floor(p); vec2 f=fract(p); f=f*f*(3.0-2.0*f); return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y); }\nvoid vertex()`);s=s.replace('hash(floor(world_pos.xz * 12.0))','mix(noise(world_pos.xz * 12.0), 0.5, clamp(length(fwidth(world_pos.xz)) * 6.0, 0.0, 1.0))').replace('hash(floor(world_pos.xz * 0.7))','noise(world_pos.xz * 0.7)');fs.writeFileSync(p,s);
